name: Check formatting

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Check that stdlib files are formatted
        run: node src/cli.js --check 'tests/liq/**/*.liq'
